FROM dart:stable AS build

WORKDIR /app

RUN apt-get update && apt-get install -y make

COPY pubspec.* ./
RUN dart pub get

COPY . .
RUN dart pub get --offline

RUN apt-get install -y curl && \
    curl -fsSL https://deb.nodesource.com/setup_lts.x | bash - && \
    apt-get install -y nodejs

COPY package.json package-lock.json /app/
RUN npm install

CMD ["npm", "start"]