version: '3.8'

services:
  runner:
    container_name: runner
    image: rgs.flutter.wtf.lab/runner
    restart: unless-stopped
    labels:
      - 'com.centurylinklabs.watchtower.enable=true'
    build:
      context: ./
      dockerfile: ./Dockerfile
    environment:
      - PORT=$PORT
    networks:
      - local
      - root_nginx

networks:
  local:
    driver: bridge
  root_nginx:
    external: true
